version: '3.8'

services:
  # The Vue frontend, now served by Nginx
  frontend:
    build:
      context: ./frontend
    # We don't need to expose ports here; the reverse proxy will connect to it.

  backend:
    build: ./backend
    restart: always # Automatically restart if it crashes
    command: npm run start # Assumes you have a 'start' script for production
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dax_optimizer_db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - db
      - redis

  worker:
    build: ./backend
    restart: always
    # Use the memory flag for production
    command: node --max-old-space-size=4096 -r ts-node/register src/jobs/optimizationWorker.ts
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dax_optimizer_db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dax_optimizer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    restart: always

volumes:
  postgres_data: